# Generated by Django 5.1 on 2024-11-10 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('launch_id', models.AutoField(primary_key=True, serialize=False)),
                ('rocket', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалён'), ('formed', 'Сформирован'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('success', models.BooleanField(null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='launch_creator', to='launchesapp.authuser')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='launch_mod', to='launchesapp.authuser')),
            ],
            options={
                'db_table': 'launches',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('satellite_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('image_url', models.URLField(null=True)),
                ('weight', models.CharField(max_length=50)),
                ('orbit', models.CharField(max_length=255)),
                ('expected_date', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='launchesapp.authuser', verbose_name='sat_creator')),
            ],
            options={
                'db_table': 'satellites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaunchSatellite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_launches', to='launchesapp.launch')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_satellites', to='launchesapp.satellite')),
            ],
            options={
                'db_table': 'launch_satellite',
                'managed': True,
                'unique_together': {('launch_id', 'satellite_id')},
            },
        ),
    ]
