# Generated by Django 5.1 on 2024-11-17 18:29

import django.db.models.deletion
import launchesapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь менеджером?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
                ('groups', models.ManyToManyField(related_name='customuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', launchesapp.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('launch_id', models.AutoField(primary_key=True, serialize=False)),
                ('rocket', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалён'), ('formed', 'Сформирован'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('success', models.BooleanField(null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='launch_creator', to='launchesapp.customuser')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='launch_mod', to='launchesapp.customuser')),
            ],
            options={
                'db_table': 'launches',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('satellite_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('image_url', models.URLField(null=True)),
                ('weight', models.CharField(max_length=50)),
                ('orbit', models.CharField(max_length=255)),
                ('expected_date', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='launchesapp.customuser', verbose_name='sat_creator')),
            ],
            options={
                'db_table': 'satellites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaunchSatellite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_launches', to='launchesapp.launch')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_satellites', to='launchesapp.satellite')),
            ],
            options={
                'db_table': 'launch_satellite',
                'managed': True,
                'unique_together': {('launch_id', 'satellite_id')},
            },
        ),
    ]
