# Generated by Django 5.1 on 2024-10-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('launch_id', models.AutoField(primary_key=True, serialize=False)),
                ('rocket', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалён'), ('formed', 'Сформирован'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'launches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaunchSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'launch_satellite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('satellite_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('image_url', models.URLField()),
                ('weight', models.CharField(max_length=50)),
                ('orbit', models.CharField(max_length=255)),
                ('expected_date', models.DateField()),
            ],
            options={
                'db_table': 'satellites',
                'managed': False,
            },
        ),
    ]
